# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

# File: simple-param.yml
parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

pool:
  vmImage: ubuntu-latest

steps:
- ${{ each parameter in parameters }}:
  - script: echo '${{ parameter.Key }} -> ${{ parameter.Value }}'
  displayName: 'Run a one-line script'



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
