# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master



# File: simple-param.yml
parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

variables:
  ${{ if eq(parameters.yesNo, true) }}:
    testVar: noWayItWorked

pool:
  vmImage: windows-latest


steps:
  - script: |
      $MyPat = '4hg47hcffdjyorchnx6s4qyo6va7zv54zrdh57axxfnpq34gpthq'
      $B64Pat = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("`:$MyPat"))
      git -c http.extraHeader="Authorization: Basic $B64Pat" clone https://kristiansmith.visualstudio.com/Tahoma%20Crest%20HOA/_git/test

  #- script: echo ${{ parameters.yesNo}}
   #         echo $(testVar)
    #displayName: 'Run a one-line script'


#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
#- task: AzureKeyVault@2
 # inputs:
  #  azureSubscription: 'TahomaCrest'
   # KeyVaultName: 'TahomaKV'
   # SecretsFilter: '*'
   # RunAsPreJob: false