# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master



# File: simple-param.yml
parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

variables:
  ${{ if eq(parameters.yesNo, true) }}:
    testVar: noWayItWorked

pool:
  vmImage: windows-latest


steps:
  - bash: echo This script could use $SYSTEM_ACCESSTOKEN
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - powershell: | 
      Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
      Write-Host "$env:SYSTEM_ACCESSTOKEN = $(System.AccessToken)"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  #- script: echo ${{ parameters.yesNo}}
   #         echo $(testVar)
    #displayName: 'Run a one-line script'


#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'TahomaCrest'
    KeyVaultName: 'TahomaKV'
    SecretsFilter: '*'
    RunAsPreJob: false