# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master



# File: simple-param.yml
parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

variables:
  ${{ if eq(parameters.yesNo, true) }}:
    testVar: noWayItWorked
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: windows-latest


steps:
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm

- script: npm ci

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Tahoma Crest'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "Hello World"'
- checkout: self
  persistCredentials: true

- script: |


  #- script: echo ${{ parameters.yesNo}}
   #         echo $(testVar)
    #displayName: 'Run a one-line script'


#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
#- task: AzureKeyVault@2
 # inputs:
  #  azureSubscription: 'TahomaCrest'
   # KeyVaultName: 'TahomaKV'
   # SecretsFilter: '*'
   # RunAsPreJob: false